import { useNavigate } from 'react-router-dom'

export default function PrivacyPolicy() {
  const navigate = useNavigate()

  return (
    <div style={{ maxWidth: 720, margin: '0 auto', padding: '48px 24px', lineHeight: 1.6, color: '#1A2744' }}>
      <button
        onClick={() => navigate(-1)}
        style={{ background: 'none', border: 'none', color: '#5B4EC8', cursor: 'pointer', fontSize: 14, marginBottom: 24, padding: 0 }}
      >
        ‹ Back
      </button>

      <h1 style={{ fontSize: 32, marginBottom: 4 }}>Privacy Policy</h1>
      <p style={{ fontStyle: 'italic', color: '#6B7280', marginBottom: 32 }}>Last updated: September 2026</p>

      <h2 style={{ fontSize: 20, marginTop: 32 }}>1. Who we are</h2>
      <p>myadaptlearn is run by an individual sole trader based in the UK. For any question about this policy or your data, contact myadaptlearn.com@gmail.com.</p>
      <p>ICO registration number: C2037550</p>

      <h2 style={{ fontSize: 20, marginTop: 32 }}>2. What we collect, and why</h2>
      <p>Here's everything myadaptlearn actually stores about you, and why:</p>
      <ul>
        <li><strong>Account information</strong> — name, nickname, email address, password (stored as a secure hash, never in plain text). Used to create and secure your account.</li>
        <li><strong>Learning preferences</strong> — education level, subject background, how you like to learn, cognitive style, exam anxiety responses, memory style, motivation, complexity preference. Used to personalise explanations to how you actually learn.</li>
        <li><strong>Learning activity</strong> — topics you study, which explanation style was used, quiz scores, your own self-rated understanding, XP and streaks. Used to run the core explain-and-quiz feature and track your progress.</li>
        <li><strong>Courses & uploaded documents</strong> — course titles and topics, and the text of any syllabus, specification or reading list you upload, including exam board and specification code if provided. Used to generate explanations grounded in your actual course material.</li>
        <li><strong>Deadlines</strong> — exam, mock, coursework, reading and essay deadlines you add. Used to build your study schedule.</li>
        <li><strong>Saved explanations</strong> — bookmarked explanations and any notes you add. Used to let you build a personal revision library.</li>
      </ul>

      <h2 style={{ fontSize: 20, marginTop: 32 }}>3. Who we share it with</h2>
      <p>We do not sell your data, and we do not share it with advertisers. A small number of services process data on our behalf, purely to run the product:</p>
      <ul>
        <li><strong>Anthropic</strong> (maker of Claude, the AI model behind myadaptlearn) — receives the topic you're asking about, your education level, and, if you've uploaded one, the relevant text from your course material, in order to generate an explanation, quiz, or flashcards.</li>
        <li><strong>Railway</strong> — hosts our database and backend server.</li>
        <li><strong>Vercel</strong> — hosts our website.</li>
      </ul>
      <p>Each of these acts as a data processor on our instructions, under their own commercial terms.</p>

      <h2 style={{ fontSize: 20, marginTop: 32 }}>4. How long we keep your data</h2>
      <p>We keep your data for as long as your account is active. If you delete your account, we delete your personal data within 30 days, except anything we're legally required to keep for longer.</p>

      <h2 style={{ fontSize: 20, marginTop: 32 }}>5. Your rights</h2>
      <p>Under UK GDPR, you have the right to access the data we hold about you, correct it if it's wrong, ask us to delete it, ask us to export it to you, and object to certain kinds of processing. To exercise any of these, email  myadaptearn.com@gmail.com. We'll respond within one month.</p>
      <p>You also have the right to complain to the ICO (ico.org.uk) if you think we've mishandled your data.</p>

      <h2 style={{ fontSize: 20, marginTop: 32 }}>6. Children's privacy</h2>
      <p>myadaptlearn is intended for use by GCSE, A-Level and university students. You must be at least 13 to create an account. If you are under 18, we recommend a parent or guardian reviews this policy with you, and no premium purchase should be made without their involvement.</p>

      <h2 style={{ fontSize: 20, marginTop: 32 }}>7. AI-generated content</h2>
      <p>Explanations, quizzes and flashcards are generated by an AI model (Claude, by Anthropic) and may occasionally be inaccurate or incomplete. Always check anything important against your actual course materials, teacher, or lecturer.</p>

      <h2 style={{ fontSize: 20, marginTop: 32 }}>8. Security</h2>
      <p>We store passwords as secure hashes, never in plain text, and follow standard practices to protect your data. No system is completely secure, and we can't guarantee absolute security.</p>

      <h2 style={{ fontSize: 20, marginTop: 32 }}>9. Cookies</h2>
      <p>myadaptlearn does not currently use tracking or advertising cookies. If this changes, we'll update this policy and ask for your consent where required.</p>

      <h2 style={{ fontSize: 20, marginTop: 32 }}>10. Changes to this policy</h2>
      <p>We may update this policy as the product changes. Any update will be posted here with a new "last updated" date.</p>

      <h2 style={{ fontSize: 20, marginTop: 32 }}>11. Contact</h2>
      <p style={{ marginBottom: 48 }}> myadaptlearn.com@gmail.com — ICO registration number: C2037550</p>
    </div>
  )
}
