import { useNavigate } from 'react-router-dom'

export default function TermsOfUse() {
  const navigate = useNavigate()

  return (
    <div style={{ maxWidth: 720, margin: '0 auto', padding: '48px 24px', lineHeight: 1.6, color: '#1A2744' }}>
      <button
        onClick={() => navigate(-1)}
        style={{ background: 'none', border: 'none', color: '#5B4EC8', cursor: 'pointer', fontSize: 14, marginBottom: 24, padding: 0 }}
      >
        ‹ Back
      </button>

      <h1 style={{ fontSize: 32, marginBottom: 4 }}>Terms of Use</h1>
      <p style={{ fontStyle: 'italic', color: '#6B7280', marginBottom: 32 }}>Last updated: September 2026</p>

      <h2 style={{ fontSize: 20, marginTop: 32 }}>1. Acceptance</h2>
      <p>By creating an account or using myadaptlearn, you agree to these terms.</p>

      <h2 style={{ fontSize: 20, marginTop: 32 }}>2. What myadaptlearn is</h2>
      <p>myadaptlearn explains topics in a style suited to how you learn, generates quizzes and flashcards, and helps you schedule revision around your own deadlines and materials.</p>
      <p><strong>myadaptlearn is for understanding and revising material — it is not a tool for producing your homework, coursework or essays for you.</strong> You must not use it, and we may suspend accounts that use it, to generate text intended to be submitted as your own academic work.</p>

      <h2 style={{ fontSize: 20, marginTop: 32 }}>3. Accounts</h2>
      <p>You must provide accurate information when registering, and you're responsible for keeping your password secure. You must be at least 13 to use myadaptlearn.</p>
      <p>This service is currently in beta. Features may change, break, or be removed without notice, and we may need to reset the database during testing. Please don't rely on it for anything exam-critical yet.</p>

      <h2 style={{ fontSize: 20, marginTop: 32 }}>4. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>use the service to generate content for submission as your own coursework, homework or exam answers</li>
        <li>attempt to bypass usage limits or extract data you're not entitled to</li>
        <li>upload content that is illegal, infringes someone else's rights, or contains someone else's personal data without their consent</li>
        <li>use the service in a way that violates Anthropic's usage policies for the underlying AI model</li>
      </ul>

      <h2 style={{ fontSize: 20, marginTop: 32 }}>5. AI accuracy</h2>
      <p>Explanations, quizzes and scheduling suggestions are generated by AI and may contain errors, may not always match your specific exam board's requirements precisely, and should not be your only source of revision material.</p>

      <h2 style={{ fontSize: 20, marginTop: 32 }}>6. Your content</h2>
      <p>You keep ownership of anything you upload — syllabuses, notes, documents. By uploading it, you give us permission to process it (including sending relevant parts to Anthropic's API) solely to provide the explanation, quiz, and scheduling features to you.</p>

      <h2 style={{ fontSize: 20, marginTop: 32 }}>7. Availability</h2>
      <p>We don't guarantee the service will always be available, especially during this beta period. We may suspend or discontinue the service, or your account, at any time, particularly for violations of these terms.</p>

      <h2 style={{ fontSize: 20, marginTop: 32 }}>8. Liability</h2>
      <p>myadaptlearn is provided as-is, without warranties. To the extent permitted by law, we're not liable for indirect or consequential losses — including exam results — arising from use of the service.</p>

      <h2 style={{ fontSize: 20, marginTop: 32 }}>9. Governing law</h2>
      <p>These terms are governed by the laws of England and Wales.</p>

      <h2 style={{ fontSize: 20, marginTop: 32 }}>10. Changes to these terms</h2>
      <p>We may update these terms as the product develops. Continued use after a change means you accept the new terms.</p>

      <h2 style={{ fontSize: 20, marginTop: 32 }}>11. Contact</h2>
      <p style={{ marginBottom: 48 }}> MyAdaptLearn@gmail.com</p>
    </div>
  )
}
